version: '3.8'

services:
  neo4j:
    image: neo4j:5.19.0
    container_name: neo4j
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_dbms_memory_transaction_total_max=4G
    volumes:
      - ./data:/var/lib/neo4j/import
      - neo4j-data:/data
    restart: unless-stopped

  embeddings_worker:
    build: .
    container_name: embeddings_worker
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./embeddings_worker/.env:/app/.env
    depends_on:
      - neo4j
    restart: unless-stopped

volumes:
  neo4j-data: